apiVersion: v1
kind: Template
metadata:
  name: kubia
  annotations:
    description: "Description ${NAME}"
    iconClass: "icon-redis"
    tags: "database,nosql"
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ${NAME} 
      version: v1
    name: kubia
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: ${NAME}
        version: v1
    template:
      metadata:
        name: ${NAME}

        labels:
          app: ${NAME}
          version: v1
      spec:
        containers:
        - image: luksa/kubia:v1
          name: nodejs
          ports:
          - name: http
            containerPort: ${{TARGET_PORT}}
            protocol: TCP

- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    ports:
    - name: http
      port: ${{PORT}}
      targetPort: ${{TARGET_PORT}}
    selector:
      app: ${NAME}

### Шаблон Route - выделение внешнего URL для сервиса, к которому запросы будут ходить извне через балансировщик и haproxy кластера
- kind: Route
  apiVersion: v1
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 360s
    name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
  spec:
    port:
      targetPort: http
    tls:
      termination: edge
      key: |-
        ${KEY}
      insecureEdgeTerminationPolicy: Allow
    to:
      kind: Service
      name: ${NAME}
      weight: 100
    wildcardPolicy: None
parameters:
  - name: NAME
    description: Name of MicroService
    displayName: Name of service
  - name: PORT
    description: Port
  - name: TARGET_PORT
    description: Target port
  - name: KEY
